### ISSUE TITLE
Gang Section wont work

### ISSUE THREAD

**Issue by MkZ0ck** [Cyberbyte-Studios/CyberWorks-3#7] opened 2018-01-23 11:48 UTC
Hi I installed CW3 on my WindowsServer on a Apache WebServer. I have the problem, when I install the php and do all my login stuff there comes to errors up and the gang section in the admin menu wont work
![error](https://user-images.githubusercontent.com/25302810/35274150-5851b882-003b-11e8-9215-04854dbd57e6.PNG)
![phperror](https://user-images.githubusercontent.com/25302810/35274217-8fd58da6-003b-11e8-989f-8add047b7ff3.PNG)

If I'am deleting my gangs table in Database, and create a new test record I can access it in the Webinterface but when im trying to edit it the error above comes up and comes again when I want to access the gang section until I delete the record in Database.

Error is also reproduce able on Conntainers and Houses section.

I hope someone find something to help me.

Greeting

**Comment by cammygames** [comment] 2018-01-23 22:55
What version of altis life are you trying to use. Currently we only support this database schema. https://github.com/AsYetUntitled/Framework/blob/master/altislife.sql

**Comment by MkZ0ck** [comment] 2018-01-24 05:45
I'm using the 5.0 of Altis Life and it should be that sql file you postet, but we are using so extra tables for an Actionhouse and Dynmarket.

**Comment by cammygames** [comment] 2018-01-27 06:42
If you send me the log file from the logs folder over discord i will take a look and see if i can resolve your issue.

**Comment by MkZ0ck** [comment] 2018-01-29 14:04
Hi, here I have the important errors: https://drive.google.com/open?id=1zHFGxapdZt_RJdZzaeAg1aFqCe3W4Cgb every thing there is like a loop I have about 200 of this errors. I hope you'll find something.

**Comment by cammygames** [comment] 2018-01-31 10:57
Could you send me the sturcture of your gangs table please. There appears to be an issue with the getOwnerIDAttribute function returing null. This is generally caused by the colum name in the table being different from what it is looking for.

**Comment by MkZ0ck** [comment] 2018-01-31 12:11
Hi, I give you here the hole structure of the database. Don't worry I was using the old Cyberworks version on my server. https://drive.google.com/open?id=19-oCui6AiZh42SNy5c5qLrwpA1DGUsq-

**Comment by cammygames** [comment] 2018-01-31 20:09
Thanks for the db, could you also send over the data for the gangs table.

**Comment by MkZ0ck** [comment] 2018-01-31 20:18
https://drive.google.com/open?id=15Zn_ZGaGG1WuiV4mptgnpCxc5XZAs78Z

**Comment by cammygames** [comment] 2018-02-01 13:19
could i get the data as SQL please. i need to ensure the data is what i expected it to be with its correct formatting.

**Comment by MkZ0ck** [comment] 2018-02-01 16:23
I hope this time its the right thing :D https://drive.google.com/open?id=1xTtCPJHTbaFilcTAd99Ddp0yJFI_RmfF

**Comment by cammygames** [comment] 2018-02-02 09:08
The data in your gang section doesn't seem to match what i expected it to be. I thought members was an array. something like the following. "[`000000000`]"  was the data you sent over data you added or what was produced by creating a gang in game.

**Comment by MkZ0ck** [comment] 2018-02-02 11:54
The data in the sql I send you was added by myself, but the gamecreated record I like you said an array in this format "[`000000000`]". I also tried to use the Webinterface with the gamecreated record but still the error from Ajax

**Comment by cammygames** [comment] 2018-02-02 17:23
So for the gang section to work you need to have a matching player to own the gang in the players table. from the data you sent me there i no matching player in the players table.

**Comment by MkZ0ck** [comment] 2018-02-04 11:31
Here I have the sql with Ingame created records: https://drive.google.com/open?id=1gaOIGhTjmrCb2p_zhe0ox61iT2nwuClT

**Comment by cammygames** [comment] 2018-02-04 15:51
In the data you sent me the owner of that gang does not exist in the players table thus the gang section isnt working as it isnt able to find the owner in the playertable. If you change the owner to the id of the only member then it will work. Just ensure the player 76561198191583870 exists in your player database.

**Comment by MkZ0ck** [comment] 2018-02-04 16:12
I see now, but can you tell me why the Owner ID changes from the Original ID (76561198191583867) to 76561198191583870 when I safe the changes. When I open the edit function there is anytime standart this ID 76561198191583867, but I have no idea from where it cames

**Comment by cammygames** [comment] 2018-02-04 16:17
i will investigate that now and get back to you shortly.

**Comment by MkZ0ck** [comment] 2018-02-04 18:01
Thanks a lot for the work man, Webinterface is very nice. Two little things, first you have to apply those changes for the House Part too and, second can you add an button for deleting Houses, Container, Vehicles and Gangs? Whould by nice. Greetings

**Comment by cammygames** [comment] 2018-02-04 18:34
Just updated #13 to include the other views. Could you possibly submit the suggestions as a feature request following the format in [ISSUE_TEMPLATE.MD](https://github.com/Cyberbyte-Studios/CyberWorks-3/blob/master/ISSUE_TEMPLATE.MD)

**Comment by MkZ0ck** [comment] 2018-02-04 18:47
I can do it but where I should put it? xD

**Comment by cammygames** [comment] 2018-02-04 18:52
just submit it as an issue but just follow the template.

**Comment by cammygames** [comment] 2018-02-04 21:04
resolved by #13

**Closed by cammygames** 2018-02-04 21:04 UTC
